# Generated by Django 5.0.14 on 2025-04-13 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug (auto-generated)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent category for nesting', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug (auto-generated)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of items currently in stock')),
                ('available', models.BooleanField(default=True, help_text='Is the product available for purchase?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category that this product belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
