# Generated by Django 5.0.14 on 2025-06-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the product', null=True, upload_to='products/images/%Y/%m/%d/'),
        ),
    ]
